### ISSUE TITLE
After I imported OpenOLAT into IntelliJ IDEA and configured, bug appeared. The program could not run.

### ISSUE THREAD

**Issue by chain155** [OpenOLAT/OpenOLAT#1]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'noteManager': Unsatisfied dependency expressed through field 'dbInstance'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.olat.core.util.WebappHelper' defined in class path resource [org/olat/core/util/_spring/utilCorecontext.xml]: Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanInitializationException: System startup aborted to to file system missconfiguration. See previous warnings in logfile and fix your Java environment. This check can be disabled by setting enforce.utf8.filesystem=false, but be aware that the decision to use a certain encoding on the filesystem is a one-time decision. You can not cange to UTF-8 later!
 
Why is that?

**Comment by chain155** [comment]
@gnaegi    @lainsr   @uhensler   @aschne

**Comment by lainsr** [comment]
It's not a bug. OpenOLAT check at start if it can write a file with special characters like ä,ü... You can set the file encoding in your VM arguments in IDEA with a -D parameter if your file system support it:
`-Dfile.encoding=UTF-8`
Or you can disable the check by setting the following properties to false in your olat.local.properties:
`enforce.utf8.filesystem=false`
We do this check because it's almost impossible to convert all the data of an OpenOLAT installation from one encoding to the other. So it's very important to set it right on a productive installation.

**Comment by gnaegi** [comment]
In case you are trying to run OpenOLAT on a Windows OS platform, please note that we do not support windows.

**Comment by tomgross** [comment]
I stumbled over that as well. Here the UTF-8 capabilites of the filesystem is checked:
https://github.com/OpenOLAT/OpenOLAT/blob/master/src/main/java/org/olat/core/util/WebappHelper.java#L451

Windows generally allows UTF-8 characters with Codepage 65001 but the pipe `|` is a reserved character (see https://docs.microsoft.com/de-de/windows/desktop/FileIO/naming-a-file#naming-conventions). What is the reason the pipe `|` is checked in `testUtf8FileSystem`?

Just to keep Windows out 😉 ?

**Comment by lainsr** [comment]
I will remove it

**Comment by gnaegi** [comment]
@tomgross no, it is not to actively keep Windows out. It is just that we do not actively support the Windows plattform and therefore are not aware of windows specific behaviour.

If you want to run OpenOLAT on windows I recommend you build a full automated test environment and run all the jUnit and Selenium testcases on a daily base against the head development.
