### ISSUE TITLE
Browser back button behaves inconsistently

### ISSUE THREAD

**Issue by tomgross** [OpenOLAT/OpenOLAT#13]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

There seems to be no consistent behavior of the back button in OpenOlat. Sometimes it works as expected, sometimes the login page is shown and sometimes a browser error occurs.

### What I did:

1. Do some various actions in OpenOlat
2. Click Browser "Back" from time to time.

### What I expect to happen:

Always go to recent page.

### What actually happened:

Sometimes it works as expected, sometimes the login page is shown and sometimes a browser error occurs.

### What version of OpenOlat I am using:

OpenOlat 13.0.0b8 (master)

**Comment by gnaegi** [comment]
"sometimes" is not specific enough. Please provide exact details. Note, OpenOLAT ist an application and not a website. In places where it has a lot of application logic it will not be possible to go back, namely when in forms or modal dialogs. 

Back must be implemented, it is not something that works out of the box due to the component addressing nature of the framework.

**Comment by tomgross** [comment]
The behavior was most likely caused by a misconfigured "NoScript" addon for Firefox and is not reproduceable now. Sorry for the noise.
