### ISSUE TITLE
How to setup openolat with oracle db

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#21]
I have created all the tables and view in my oracle db for olat and also added db credentials  in the olat.properties file. I am getting the error "Could not load JDBC driver class [oracle.jdbc.driver.OracleDriver"
What all files we need to change to make it work with oracle db

**Comment by lainsr** [comment]
OpenOlat needs to have the Oracle JDBC Driver available in the class path (in the path tomcat/lib for example). Because of licensing issues, we cannot link this driver in our maven build process or in the WAR file.

That said, Oracle support is only experimental as we don't run regularly automated tests with and we don't have OpenOlat in production with Oracle. For the best performance and reliability, we recommend to use PostgreSQL.
