### ISSUE TITLE
licence dropdown is not populating with values

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#27]
in the course creation we have one metadata tab.in that, licence value is not getting populated and is showing mandatory. default option present is missing licence
<img width="1329" alt="Screenshot 2019-08-07 at 2 50 26 PM" src="https://user-images.githubusercontent.com/5021230/62611213-c5332200-b922-11e9-9248-e860b43f4e2d.png">

**Comment by uhensler** [comment]
"Missing license" means "License not available". I guess you have selected a license earlier, but this license is not available anymore because the license was deactivated in the licenses configuration.

In that case you have to select an other license (or set it to "no license")! Because you have to change the license, the field is mandatory.
