### ISSUE TITLE
Error in eportfolio link under evidence of achievement link in user profile

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#34]
When clicking on the eportfolio link under evidence of achievement in profile
Path
Profile-evidence of achievement-eportfolio
It is displaying a pop up window on saving the form I am getting an error.
Error is null constaint error 
Cannot insert null into O_PF_MEDIA.P_BUSINESS_PATH. Y it's inserting null values to this column

**Comment by gnaegi** [comment]
- Which version do you use
- what kind of learning resource do you try to add ass e-portfolio artefact?

I can not reproduce this in our environment.

**Comment by gnaegi** [comment]
My colleague just told me that you are using Oracle. This is most likely the reason for the error. 

Oracle is not officially supported. See https://github.com/OpenOLAT/OpenOLAT/issues/21 for more info on this. 

If you / your organisation is interested in funding the Oracle compatibility, please get in touch with me privately. To secure an Oracle compatibility the following needs to be funded: 

 **One-time funding**
- Oracle license for development and testing infrastructure
- Setup automated unit and selenium tests for the major development branches in our continuous development infrastructure
- Test the app with Oracle, fix all the issues

**Yearly recurring funding**
-  Maintaining utomated unit and selenium tests for the major development branches in our continuous development infrastructure

Many problems with Oracle are like the one your encountered: empty string handling is different with Oracle than with other databases. We recommend using Postgres instead of Oracle. Even for very large installations Postgres performs nicely and it is a lot cheaper...

**Comment by lainsr** [comment]
The issue will be fixed in 14.1.0 (OO-4197)
