### ISSUE TITLE
Back button not working

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#36]
There seems to be no consistent behavior of the back button in OpenOlat. Sometimes it works as expected, sometimes the login page is shown and sometimes a browser error occurs. I have nt added any plugin in my browset

What I did:
Do some various actions in OpenOlat
Click Browser "Back" from time to time.
What I expect to happen:
Always go to recent page.

What actually happened:
Sometimes it works as expected, sometimes the login page is shown and sometimes a browser error occurs

**Comment by lainsr** [comment]
Back button must be implemented. I doesn't come "naturally". If you have an issue with it, please say exactly where and which path you follow until you click back.

**Comment by gnaegi** [comment]
"sometimes" or "from time to time" is not specific enough for a bug description. Please describe a scenario step by step how it can be reproduced. Otherwise we will not be able to fix the problem. 

Also note that back will never be implemented for modal dialogs and in some scenarios back is not available by design such as in the e-assessment tool. In addition, back will never perform an undo, this means back will have no effect on actions-links. We implement back only for navigation-links.
