### ISSUE TITLE
Documentation doesn't match current software 

### ISSUE THREAD

**Issue by aquast** [OpenOLAT/OpenOLAT#50]
Dear Developers,

I tried to deploy OpenOlat within a tomcat 8 environment. Unfortunately all docs provided refer to OpenOlat version 10.x which seems to be far away from the current 14.1 version.

Can you please provide a more recent documentation with an additional focus on deployment, rather then running OpenOlat within eclipse. 

I also really like to contribute to docs, if I'm able to operate and understand the OpenOlat current state of art :-)

Thanks in advance,
a.

**Comment by gnaegi** [comment]
On https://github.com/OpenOLAT/OpenOLAT you will find the link **Ressource -> Installation** which points to https://www.openolat.com/fileadmin/adminwiki/_START_.html. There you will find the instructions how to install OpenOlat. The instructions on GitHub are for developers who want to install it in their development IDE: "**Look for Installation of OpenOLAT with PostgreSQL (recommended)**"

**Comment by aquast** [comment]
My impression was the docs you mentioned  (https://www.openolat.com/fileadmin/adminwiki/_START_.html.) were not up to date. 
I documented the deployment for Version 14.1 with PostgreSQL. Please find my PR for that.

**Comment by gnaegi** [comment]
Hi 

Thanks for your effort, however the separation of development (GIT) and production (openolat.com) is intentional. The current documentation is maintained as a wiki in the OpenOlat community system and then exported to make it available on the website. Besides the deployment it contains many more information about how to update, special confic topics such as Shibboleth setups etc. 

We are currently setting up a new OpenOlat homepage and will change and move documentation  and information during that effort. Maybe we can incorporate your pull request at that time. What we don't want are two different deployment documentations, one in the admin wiki and one in the code. 

From a developer standpoint we do not want to have a deployment documentation that has links in it for specific release versions, this must be updated for every release which is cumbersome and will get forgotten quickly. A generic approach must work.

**Comment by aquast** [comment]
Hi,
its on your's how to handle documentation. For my (developer too) perspective it's a little bit strange if I need to check all installation steps documented (e.g for Tomcat params needed to fix caching) for a deployment that should be the final goal of each development ;) . 

Best, a.

**Comment by gnaegi** [comment]
We will remove the wiki doc for installation and move everything to a new docu center for OpenOlat. You can preview the new doc here: https://docs.openolat.org/admin-manual/installation/installGuide/
