### ISSUE TITLE
Browser specifications for running automatic acceptance tests

### ISSUE THREAD

**Issue by tomgross** [OpenOLAT/OpenOLAT#54]
I've seen failing OpenOlat Selenium acceptance tests with the newest version of Firefox (72.0.2), which pass on the ESR build (68.4.2esr) on my Mac. My geckodriver version is 0.24.0.

- What are the recommended version of Firefox and Chrome together with geckodriver and chromedriver to run the Selenium acceptance tests?
- Are there any other browsers the Selenium tests run on?

**Comment by lainsr** [comment]
- I run them always with the last version of Chrome ( 80... ) and Firefox (72.0.2) on Linux. The drivers are automatically downloaded by Arquillian, always the last versions. I don't have problems running them on my mac, but I do it mostly within Eclipse.
- Firefox and Chrome are supported. It's not possible to run several Safaris at the same time which excludes it for a lot of my tests and IE 11 or Edge needs a complicated setup to be run. Edge Chromium is less interessant because it's very similar to Chrome and not wildly used.
