### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by pojianchaliao** [OpenOLAT/OpenOLAT#86]
Dear Developers,
       After openolat is deployed locally, the following error message appears on the orders page in coaching  
       
      >>>>>>>>>>>>>>>>>>>>>>>>>> component segmentCmp could not be found to be rendered!  

      please how can i solve it

**Comment by gnaegi** [comment]
Hi

- which OpenOlat version do you use?
- it this a fresh installation or an updated system? if updated, did all your database upgrades go through?
- where in the coaching tool exactly does the error appear (which tab in the order site)?
- can you please attach a screenshot 

Cheers
Florian

**Comment by pojianchaliao** [comment]
> Hi
> 
> * which OpenOlat version do you use?
> * it this a fresh installation or an updated system? if updated, did all your database upgrades go through?
> * where in the coaching tool exactly does the error appear (which tab in the order site)?
> * can you please attach a screenshot
> 
> Cheers Florian

Duplicate of #

**Comment by pojianchaliao** [comment]
Hi

1. I used the Default branch --master   ，Should I use versions of other branches？ 
2. it is my first time to use this system
3. ![企业微信截图_16424694059508](https://user-images.githubusercontent.com/60560615/149858486-5f0442df-eed3-4652-911a-db206269308c.jpg)

Thanks
pojianchaliao

**Comment by pojianchaliao** [comment]
Hi Team
    Does the OPENOLAT system support be assimilated by the Chinese Conveniently ?

THANKS
pojianchaliao

**Comment by gnaegi** [comment]
There is a Chinese translation, however it is not complete. If your are interested to translate into Chinese you can do this on our translation server. Let me know. 

Regarding your problem: no idea, please have a look at your olat.log and search for errors.

**Comment by twinyk** [comment]
肯定支持
















At 2022-01-18 16:36:03, "pojianchaliao" ***@***.***> wrote:

Hi Team
Does the OPENOLAT system support be assimilated by the Chinese Conveniently ?

THANKS
pojianchaliao

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by twinyk** [comment]
the version of OLAT from 5-7.2 is done by me ten years ago. let do simple Chinese translation and traditional Chinese translate. Please give me translation server account again. thank you .Florian Gnägi


wubin
















At 2022-01-19 05:39:10, "Florian Gnägi" ***@***.***> wrote:

There is a Chinese translation, however it is not complete. If your are interested to translate into Chinese you can do this on our translation server. Let me know.

Regarding your problem: no idea, please have a look at your olat.log and search for errors.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gnaegi** [comment]
Hi Wubin

Great to hear that you want to continue with the Chinese translation. I gave Mandy our Email address, she will contact you in the next days to arrange access to our translation server. 

Regards
Florian

**Comment by pojianchaliao** [comment]
Hi teams
     I'm sorry I need to finish this project in the shortest time, so I don't have much time to spend on translation

Best wishes

**Comment by pojianchaliao** [comment]
> 肯定支持 At 2022-01-18 16:36:03, "pojianchaliao" ***@***.***> wrote: Hi Team Does the OPENOLAT system support be assimilated by the Chinese Conveniently ? THANKS pojianchaliao — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

请问 OLAT 5-7.2  哪里可以找到这个版本？我在openolat这个仓库里没看到这个版本， 今天查看了其他同类型的平台还是openolat的前端页面比较符合我的审美，想接着试试

**Comment by gnaegi** [comment]
Addendum: in the meantime I could reproduce the problem. It only happens with a user that has no course associated. This happens normally only in a very fresh installation and mostly only with the admin user. This edge case is now fixed, a proper message will be shown in the next release instead of the error. 

You can follow the issue here: https://jira.openolat.org/browse/OO-5962

**Comment by twinyk** [comment]
前期版本，已经部署在百度内部，早期百度企业大学就是用的olat内核，我们修改了很多的bug. 百度一定有源码。
















在 2022-01-20 00:36:59，"pojianchaliao" ***@***.***> 写道：

肯定支持 At 2022-01-18 16:36:03, "pojianchaliao" @.> wrote: Hi Team Does the OPENOLAT system support be assimilated by the Chinese Conveniently ? THANKS pojianchaliao — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: @.>

请问 OLAT 5-7.2 哪里可以找到这个版本？我在openolat这个仓库里没看到这个版本， 今天查看了其他同类型的平台还是openolat的前端页面比较符合我的审美，想接着试试

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by twinyk** [comment]
你们没有时间 ，我们有，不过 欧洲那边 olat好像和openolat 在几年前闹翻了。 marion web也出走美国了。。。。

几万条翻译 一个月就完事了。













At 2022-01-19 23:04:49, "pojianchaliao" ***@***.***> wrote:

Hi teams
I'm sorry I need to finish this project in the shortest time, so I don't have much time to spend on translation

Best wishes

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by twinyk** [comment]
Thank you Florian,


    my team would do it within 2 weeks, I have a lot of staff now.  and next week would be Chinese new year, and we both have a short weekends, hope Mandy can give me the translation server account as soon as possible.


wu bin
















At 2022-01-19 19:23:06, "Florian Gnägi" ***@***.***> wrote:

Hi Wubin

Great to hear that you want to continue with the Chinese translation. I gave Mandy our Email address, she will contact you in the next days to arrange access to our translation server.

Regards
Florian

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gnaegi** [comment]
Hi 

Please do not start discussions in other languages than english, thank you.  Does Baidu still use OpenOlat actively?

 @twinyk Mandy did already contact you last week, please check your mail.

**Comment by twinyk** [comment]
Currently, Baidu is still using olat as core resource management LMS, but they changed some user interfaces.  learn.baidu.com, is the internal address.







At 2022-01-24 17:00:47, "Florian Gnägi" ***@***.***> wrote:

Hi

Please do not start discussions in other languages than english, thank you. Does Baidu still use OpenOlat actively?

@twinyk Mandy did already contact you last week, please check your mail.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gnaegi** [comment]
@twinyk cool, great to know. Do they have plans to update to a new OpenOlat version? It would be great to put Baidu on the OpenOlat known installation list.

**Comment by twinyk** [comment]
@Florian, currently they are still using the older version of OLAT, I have left Baidu for many years, as you know if there is no Chinese Version the local staff can not configure and use the OLAT since 2012 I have done little thing about translation.
You can definitely add Baidu as an installation list member. And we also adapt Opencast and Matthrehorn Live videocast as internal learning resource generators.





















At 2022-01-25 16:27:17, "Florian Gnägi" ***@***.***> wrote:

@twinyk cool, great to know. Do they have plans to update to a new OpenOlat version? It would be great to put Baidu on the OpenOlat known installation list.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
