### ISSUE TITLE
Register user by api , and send to the created user on email username and password 

### ISSUE THREAD

**Issue by geoorgee20** [OpenOLAT/OpenOLAT#94]
It is possible to send an email to an user by api where i could send him the password and the username to connect to the platform.
Thank you

**Comment by gnaegi** [comment]
Sorry, no, OpenOlat does not know the password in cleartext and thus can not send it to a user. The workflow would be like this: 

1. Your app creates a new password
2. Set the new password via REST API using this endpoint:  
`POST   /users/{identityKey}/authentications/password`
3. Your app sends the user a mail with the new password

But please reconsider sending the password at all! A better approach ist to send the user a link where he can set a new password instead. This is more secure than sending password and you can make sure only the user has ever seen his on password, not even you need to know it. 

Use the `/pwchange` endpoint for this.

You will then get a registrationKey that you can use to in a link to set the new password. The URL looks like this: 
`https://your.domain/dmz/pwchange/index.html?key={registrationKey}&language=en`

Send this mail to the user instead of the clear text password.

**Comment by geoorgee20** [comment]
Thank you , 
I will try to make it work with this approach.
